import { Event } from 'react-big-calendar';
import { EventType } from './enums/eventType';

const now = new Date();

export default [
  {
    id: 1,
    title: 'Long Event',
    start: new Date(2015, 3, 7),
    end: new Date(2015, 3, 10),
    resource: EventType.CALL,
  },
  {
    id: 2,
    title: 'DTS STARTS',
    start: new Date(2016, 2, 13),
    end: new Date(2016, 2, 20),
    resource: EventType.OPERATION,
  },
  {
    id: 3,
    title: 'DTS ENDS',
    start: new Date(2016, 10, 6),
    end: new Date(2016, 10, 13),
    resource: EventType.CALL,
  },
  {
    id: 4,
    title: 'Some Event',
    start: new Date(2015, 3, 9),
    end: new Date(2015, 3, 9),
    allDay: true,
    resource: EventType.OPERATION,
  },
  {
    id: 5,
    title: 'Conference',
    start: new Date(2015, 3, 11),
    end: new Date(2015, 3, 13),
    desc: 'Big conference for important people',
    resource: EventType.CALL,
  },
  {
    id: 28,
    title: 'Brainstorming Session',
    start: new Date(2015, 3, 12, 9, 0),
    end: new Date(2015, 3, 12, 10, 0),
    desc: 'Creative discussion on new project ideas',
    resource: EventType.CALL,
  },
  {
    id: 29,
    title: 'Client Presentation',
    start: new Date(2015, 3, 12, 14, 0),
    end: new Date(2015, 3, 12, 15, 30),
    desc: 'Presenting the latest progress to the client',
    resource: EventType.OPERATION,
  },
  {
    id: 30,
    title: 'Team Standup',
    start: new Date(2015, 3, 12, 15, 45),
    end: new Date(2015, 3, 12, 16, 15),
    desc: 'Quick team sync on project progress',
    resource: EventType.CALL,
  },
  {
    id: 31,
    title: 'Product Review',
    start: new Date(2015, 3, 12, 17, 0),
    end: new Date(2015, 3, 12, 18, 0),
    desc: 'Reviewing the latest product features',
    resource: EventType.OPERATION,
  },
  {
    id: 32,
    title: 'Call',
    start: new Date(2015, 3, 12, 17, 30),
    end: new Date(2015, 3, 12, 18, 0),
    desc: 'Reviewing the latest product features',
    resource: EventType.CALL,
  },
  {
    id: 33,
    title: 'Code Review',
    start: new Date(2015, 3, 10, 10, 0),
    end: new Date(2015, 3, 10, 11, 0),
    desc: 'Reviewing code changes for the new feature',
    resource: EventType.OPERATION,
  },
  {
    id: 34,
    title: 'Team Meeting',
    start: new Date(2015, 3, 10, 11, 15),
    end: new Date(2015, 3, 10, 12, 0),
    desc: 'Syncing up with the team on the current tasks',
    resource: EventType.CALL,
  },
  {
    id: 35,
    title: 'Client Call',
    start: new Date(2015, 3, 10, 13, 0),
    end: new Date(2015, 3, 10, 14, 0),
    desc: 'Discussing project updates with the client',
    resource: EventType.CALL,
  },
  {
    id: 36,
    title: 'Development Session',
    start: new Date(2015, 3, 11, 9, 0),
    end: new Date(2015, 3, 11, 11, 0),
    desc: 'Working on implementing new features',
    resource: EventType.OPERATION,
  },
  {
    id: 37,
    title: 'Sprint Planning',
    start: new Date(2015, 3, 11, 11, 15),
    end: new Date(2015, 3, 11, 12, 0),
    desc: 'Planning tasks for the next sprint',
    resource: EventType.OPERATION,
  },
  {
    id: 38,
    title: 'Design Discussion',
    start: new Date(2015, 3, 11, 14, 0),
    end: new Date(2015, 3, 11, 15, 30),
    desc: 'Discussing design updates for the project',
    resource: EventType.CALL,
  },
  {
    id: 39,
    title: 'Daily Sync',
    start: new Date(2015, 3, 12, 8, 30),
    end: new Date(2015, 3, 12, 9, 0),
    desc: 'Quick check-in with the team',
    resource: EventType.CALL,
  },
  {
    id: 40,
    title: 'Product Demo',
    start: new Date(2015, 3, 12, 10, 0),
    end: new Date(2015, 3, 12, 11, 0),
    desc: 'Demonstrating the latest product updates to the team',
    resource: EventType.OPERATION,
  },
  {
    id: 41,
    title: 'Client Feedback',
    start: new Date(2015, 3, 12, 13, 30),
    end: new Date(2015, 3, 12, 14, 30),
    desc: 'Gathering feedback from the client on the project',
    resource: EventType.CALL,
  },
  {
    id: 14,
    title: 'Today',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() + 3)),
    resource: EventType.OPERATION,
  },
  {
    id: 15,
    title: 'Point in Time Event',
    start: now,
    end: now,
    resource: EventType.CALL,
  },
  {
    id: 16,
    title: 'Video Record',
    start: new Date(2015, 3, 14, 15, 30),
    end: new Date(2015, 3, 14, 19, 0),
    resource: EventType.OPERATION,
  },
  {
    id: 17,
    title: 'Dutch Song Producing',
    start: new Date(2015, 3, 14, 16, 30),
    end: new Date(2015, 3, 14, 20, 0),
    resource: EventType.CALL,
  },
  {
    id: 23,
    title: 'Go to the gym',
    start: new Date(2015, 3, 14, 18, 30),
    end: new Date(2015, 3, 14, 20, 0),
    resource: EventType.OPERATION,
  },
  {
    id: 24,
    title: 'DST ends on this day (Europe)',
    start: new Date(2022, 9, 30, 0, 0),
    end: new Date(2022, 9, 30, 4, 30),
    resource: EventType.CALL,
  },
  {
    id: 25,
    title: 'DST ends on this day (America)',
    start: new Date(2022, 10, 6, 0, 0),
    end: new Date(2022, 10, 6, 4, 30),
    resource: EventType.OPERATION,
  },
  {
    id: 26,
    title: 'DST starts on this day (America)',
    start: new Date(2023, 2, 12, 0, 0),
    end: new Date(2023, 2, 12, 4, 30),
    resource: EventType.CALL,
  },
  {
    id: 27,
    title: 'DST starts on this day (Europe)',
    start: new Date(2023, 2, 26, 0, 0),
    end: new Date(2023, 2, 26, 4, 30),
    resource: EventType.OPERATION,
  },
] as (Event & { id: number; desc?: string })[];
